version: '2.1'

services:
  minecraft:
    build: .
    volumes:
      - minecraft-data:/data
    ports:
      - "25565:25565"
      - "25575:25575"
    restart: always
    image: chpoit/ozone3-minecraft:PO3-3.0.41
    # image: chpoit/ozone3-minecraft:latest

volumes:
  minecraft-data:
    driver: local
